version: "3.9"
services:
  swayfxbuild:
    container_name: swayfxbuild
    working_dir: /build
    build: .
    image: swayfxbuild:latest
    environment:
      - WLROOTSVERSION=0.19.0
      - WLROOTSLIBVERSION=0.19
      - SWAYFXVERSION=0.5.2
      - SCENEFXVERSION=0.4.1
      - SCENEFXLIBVERSION=0.4
    volumes:
      - ./opt:/opt

