#ifndef _SWAY_SHADERS_H
#define _SWAY_SHADERS_H

// Colored quads
const GLchar quad_vertex_src[] =
"uniform mat3 proj;\n"
"uniform vec4 color;\n"
"attribute vec2 pos;\n"
"attribute vec2 texcoord;\n"
"varying vec4 v_color;\n"
"varying vec2 v_texcoord;\n"
"\n"
"void main() {\n"
"	gl_Position = vec4(proj * vec3(pos, 1.0), 1.0);\n"
"	v_color = color;\n"
"	v_texcoord = texcoord;\n"
"}\n";

const GLchar quad_fragment_src[] =
"precision mediump float;\n"
"varying vec4 v_color;\n"
"varying vec2 v_texcoord;\n"
"\n"
"void main() {\n"
"	gl_FragColor = v_color;\n"
"}\n";

// Textured quads
const GLchar tex_vertex_src[] =
"uniform mat3 proj;\n"
"attribute vec2 pos;\n"
"attribute vec2 texcoord;\n"
"varying vec2 v_texcoord;\n"
"\n"
"void main() {\n"
"	gl_Position = vec4(proj * vec3(pos, 1.0), 1.0);\n"
"	v_texcoord = texcoord;\n"
"}\n";

const GLchar tex_fragment_src_rgba[] =
"precision mediump float;\n"
"varying vec2 v_texcoord;\n"
"uniform sampler2D tex;\n"
"uniform float alpha;\n"
"\n"
"uniform float width;\n"
"uniform float height;\n"
"uniform vec2 position;\n"
"uniform float radius;\n"
"uniform float border_thickness;\n"
"\n"
"float RectSDF(vec2 p, vec2 b, float r) {\n"
"   vec2 d = abs(p) - b + vec2(r);\n"
"	return min(max(d.x, d.y), 0.0) + length(max(d, 0.0)) - r;\n"
"}\n"
"\n"
"void main() {\n"
"   vec4 border_color = vec4(1.0, 1.0, 0.0, 1.0);\n"
"	float half_border_thickness = border_thickness / 2.0;\n"
"	vec2 size = vec2(width, height);\n"
"	vec2 half_size = vec2(width, height) / 2.0;\n"
"	vec2 pos = vec2(position.x - width * 0.5 , position.y - height * 0.5);\n"
"	vec2 center = gl_FragCoord.xy - pos - size;\n"
"\n"
"   float dist = RectSDF(center, half_size, radius);\n"
"\n"
"   vec4 from_color = border_color;\n"
"   vec4 to_color = vec4(0.0);\n"
"\n"
"	if (half_border_thickness > 0.0) {\n"
"		if (dist < 0.0) {\n"
"			to_color = texture2D(tex, v_texcoord) * alpha;\n"
"		}\n"
"\n"
"		dist = abs(dist) - half_border_thickness;\n"
"	} else {\n"
"		from_color = texture2D(tex, v_texcoord) * alpha;\n"
"	}\n"
"\n"
"	float blend_amount = smoothstep(-1.0, 1.0, dist);\n"
"	gl_FragColor = mix(from_color, to_color, blend_amount);\n"
"}\n";

const GLchar tex_fragment_src_rgbx[] =
"precision mediump float;\n"
"varying vec2 v_texcoord;\n"
"uniform sampler2D tex;\n"
"uniform float alpha;\n"
"\n"
"uniform float width;\n"
"uniform float height;\n"
"uniform vec2 position;\n"
"uniform float radius;\n"
"uniform float border_thickness;\n"
"\n"
"void main() {\n"
"	gl_FragColor = vec4(texture2D(tex, v_texcoord).rgb, 1.0) * alpha;\n"
"   vec2 corner_distance = min(gl_FragCoord.xy - position, position + vec2(width, height) - gl_FragCoord.xy);\n"
"   if (max(corner_distance.x, corner_distance.y) < radius) {\n"
"		float d = radius - distance(corner_distance, vec2(radius, radius));\n"
"		float smooth = smoothstep(-1.0f, 1.0f, d);\n"
"		gl_FragColor = mix(vec4(0), gl_FragColor, smooth);\n"
"   }\n"
"}\n";

const GLchar tex_fragment_src_external[] =
"#extension GL_OES_EGL_image_external : require\n\n"
"precision mediump float;\n"
"varying vec2 v_texcoord;\n"
"uniform samplerExternalOES texture0;\n"
"uniform float alpha;\n"
"\n"
"uniform float width;\n"
"uniform float height;\n"
"uniform vec2 position;\n"
"uniform float radius;\n"
"uniform float border_thickness;\n"
"\n"
"void main() {\n"
"	gl_FragColor = texture2D(texture0, v_texcoord) * alpha;\n"
"   vec2 corner_distance = min(gl_FragCoord.xy - position, position + vec2(width, height) - gl_FragCoord.xy);\n"
"   if (max(corner_distance.x, corner_distance.y) < radius) {\n"
"		float d = radius - distance(corner_distance, vec2(radius, radius));\n"
"		float smooth = smoothstep(-1.0f, 1.0f, d);\n"
"		gl_FragColor = mix(vec4(0), gl_FragColor, smooth);\n"
"   }\n"
"}\n";

#endif
